### ISSUE TITLE
xxxxx.redis.cache.chinacloudapi.cn:6380. Name or service not known.

### ISSUE THREAD

**Issue by zzyykk123456** [MicrosoftDocs/azure-docs.zh-cn#639]
OS: windows 10
Azure Redis  version : 3.2.7
python   Redis  version:3.3.8

--------------------以下是python 代码--------------------
import redis
  redis_conn = redis.StrictRedis(
        host="xxxxxxxxxx.redis.cache.chinacloudapi.cn",
        port=6380,
        db=13,
        password="xxxxxxxxxx",
        ssl=True,
        decode_responses=True)

--------------------以下是错误信息--------------------
Traceback (most recent call last):
  File "c:\users\adminstrator\envs\xxxxxxxxxx_env\lib\site-packages\celery\app\trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "c:\users\adminstrator\envs\xxxxxxxxxx_env\lib\site-packages\celery\app\trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "C:\xxxxxxxxxx\projects\xxxxxxxxxx\xxxxxxxxxx.py", line 36, in brower_analy
    album_1 = redis_conn.get('aaa:1')
  File "c:\users\adminstrator\envs\xxxxxxxxxx_env\lib\site-packages\redis\client.py", line 1332, in get
    return self.execute_command('GET', name)
  File "c:\users\adminstrator\envs\xxxxxxxxxx_env\lib\site-packages\redis\client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "c:\users\adminstrator\envs\xxxxxxxxxx_env\lib\site-packages\redis\connection.py", line 1071, in get_connection
    connection.connect()
  File "c:\users\adminstrator\envs\xxxxxxxxxx_env\lib\site-packages\redis\connection.py", line 543, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 11001 connecting to xxxxxxxxxx.redis.cache.chinacloudapi.cn:6380. Name or service not known.

--------------------另外说明--------------------

本地连接是可以的：
import redis
  redis_conn = redis.StrictRedis(
        host="127.0.0.1",
        port=6379,
        db=13,
        ssl=False,
        decode_responses=True)

补充说明：
以上测试是在定时任务celery里执行的 ，但是定时任务里 本地的Redis连接是可以的，是否和Celery有关系？如果不在定时任务里，Azure Redis 连接也是正常的。So ，what happened？

**Comment by srvbpigh** [comment]
Hello, @zzyykk123456
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@zzyykk123456

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
